// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var xzbAdminApp, xzbAdminAppControllers, xzbAdminAppServices;

  xzbAdminApp = angular.module('xzbAdminApp', ['xzbAdminApp.services', 'xzbAdminApp.controllers', 'ui.bootstrap']);

  xzbAdminApp.config([
    '$locationProvider', function($locationProvider) {
      return $locationProvider.html5Mode(true).hashPrefix("!");
    }
  ]);

  xzbAdminApp.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when("/all", {
        templateUrl: 'app/partials/all.html',
        controller: 'recentArticlesCtrl'
      });
      $routeProvider.when('/:user', {
        templateUrl: 'app/partials/user.html',
        controller: 'userArticlesCtrl'
      });
      return $routeProvider.otherwise({
        redirectTo: '/all'
      });
    }
  ]);

  xzbAdminAppControllers = angular.module('xzbAdminApp.controllers', []);

  xzbAdminAppControllers.controller('userListCtrl', function($scope, $http, $location) {
    var userPathWatch, userPathWatchAction;
    $http.get('json/users.json').success(function(data) {
      return $scope.users = data;
    });
    $scope.navClass = function(page) {
      return {
        last: this.$last,
        active: page && $scope.currentPage === page
      };
    };
    userPathWatch = function() {
      return $location.path();
    };
    userPathWatchAction = function(path) {
      return $scope.currentPage = path.split('/')[2];
    };
    $scope.$watch(userPathWatch, userPathWatchAction);
    return true;
  });

  xzbAdminAppControllers.controller('recentArticlesCtrl', function($scope, $http, $dialog) {
    $http.get('app/json/recent-articles.json').success(function(data) {
      return $scope.recent = data;
    });
    $scope.opts = {
      backdrop: true,
      keyboard: true,
      backdropFade: true,
      backdropClick: true,
      templateUrl: 'app/partials/article-list.html',
      controller: 'articleListCtrl'
    };
    $scope.openDialog = function(category) {
      var d;
      angular.extend($scope.opts, {
        resolve: {
          category: category
        }
      });
      d = $dialog.dialog($scope.opts);
      return d.open().then(function(result) {
        if (result) {
          return alert("close with result: " + result);
        }
      });
    };
    return true;
  });

  xzbAdminAppControllers.controller('articleListCtrl', function($scope, $http, dialog, category) {
    $http.get("app/json/category-" + category + ".json").success(function(data) {
      return $scope.articles = data;
    });
    $scope.articleList = {
      category: category,
      select: function(id, index) {
        this.articleId = id;
        return $scope.currentSelected = index;
      },
      change: function() {
        console.log(this.articleId);
        return dialog.close(this.articleId);
      },
      close: function() {
        return dialog.close();
      }
    };
    return true;
  });

  xzbAdminAppControllers.controller('userArticlesCtrl', function($scope, $http, $routeParams) {
    var userName;
    $scope.userName = userName = $routeParams.user;
    return $http.get("app/json/" + userName + ".json").success(function(data) {
      return $scope.delivers = data;
    });
  });

  xzbAdminAppServices = angular.module('xzbAdminApp.services', []);

}).call(this);
