make:
	export GOPATH=/home/denny/backup/essential/Dropbox/private_data/code/xiaozibao/code/postwasher; go build postwasher
run:
	export GOPATH=/home/denny/backup/essential/Dropbox/private_data/code/xiaozibao/code/postwasher; go run ./src/main.go