make:
	export GOPATH=/Users/mac/backup/essential/Dropbox/private_data/code/xiaozibao/code/filter_article/postwasher; go build postwasher
run:
	export GOPATH=/Users/mac/backup/essential/Dropbox/private_data/code/xiaozibao/code/filter_article/postwasher; go run ./src/main.go
