make:
	export GOPATH=/home/denny/backup/essential/Dropbox/private_data/xiaozibao/code/webcrawler; go build webcrawler
	export GOPATH=/home/denny/backup/essential/Dropbox/private_data/xiaozibao/code/webcrawler; go build taskgenerator

run:
	export GOPATH=/home/denny/backup/essential/Dropbox/private_data/xiaozibao/code/webcrawler; go run ./src/main.go