make:
	export GOPATH="$XZB_HOME/code/webcrawler"; go build webcrawler
	export GOPATH="$XZB_HOME/code/webcrawler"; go build taskgenerator

run:
	export GOPATH=$XZB_HOME/code/webcrawler; go run ./src/main.go
