install:
	install utility_xzb.sh /usr/bin/utility_xzb.sh
	install xzb_create_user.sh /usr/bin/xzb_create_user.sh
	install xzb_update_category.sh /usr/bin/xzb_update_category.sh
	install xzb_update_users.sh /usr/bin/xzb_update_users.sh
	install xzb_update_all.sh /usr/bin/xzb_update_all.sh
	install xzb_format_posts.sh /usr/bin/xzb_format_posts.sh
	install xzb_mq_tool.py /usr/bin/xzb_mq_tool.py
	install xzb_fetch_url.sh /usr/bin/xzb_fetch_url.sh