make:
	export GOPATH="$XZB_HOME/code/webcrawl_article/webcrawler"; go build webcrawler
	export GOPATH="$XZB_HOME/code/webcrawl_article/webcrawler"; go build taskgenerator

run:
	export GOPATH="$XZB_HOME/code/webcrawl_article/webcrawler"; go run ./src/main.go
test:
	echo "TODO test"
