CREATE DATABASE xzb CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER user_2013;

SET PASSWORD FOR user_2013 = PASSWORD("ilovechina");

GRANT ALL PRIVILEGES ON xzb.* TO "user_2013"@"localhost" IDENTIFIED BY "ilovechina";

FLUSH PRIVILEGES;
